name: Deploy

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: SSH & Run docker compose
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /root/workspace/gallery
            git pull --rebase origin main
            bash ./deploy-website.sh
